version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: shorturl-rs
    environment:
      POSTGRES_USER: enrique
      POSTGRES_PASSWORD: emarifer
      POSTGRES_DB: shorturl
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data

# docker exec -it shorturl-rs psql -U enrique -W shorturl
# Password: emarifer

# DATABASE_URL=postgres://enrique:emarifer@localhost:5432/shorturl

# MIGRATIONS:
# sqlx migrate add -r url (up & down)
# sqlx migrate run
# sqlx migrate revert (revert)
